In [3]:
import msprime as msp
L = 1_000_000
sim = msp.simulate(sample_size=2, length=L, mutation_rate=1e-8, recombination_rate=1e-9, Ne=1e4)

import numpy as np
x = []
y = []
i = 0
while i < 5000:
    L = 1_000_000
    sim = msp.simulate(sample_size=2, length=L, mutation_rate=1e-8, recombination_rate=1e-9, Ne=1e4)
    positions = np.array([v.position for v in sim.variants()])
    gaps = np.diff(positions)
    if len(gaps) <= 100:
        continue
    x.append(gaps[:50])
    y.append(gaps[50:51])
    i += 1
    
x=np.array(x)
y=np.array(y)
x=x.reshape(5000,50,1)
print("x_train shape:",x.shape)
print("y_train shape:",y.shape)

x_train shape: (5000, 50, 1)
y_train shape: (5000, 1)


In [5]:
import keras
from keras import layers

model = keras.models.Sequential()
model.add(layers.LSTM(256, input_shape=(50, 1)))
model.add(layers.Dense(100, activation='elu'))
model.add(layers.Dense(1, activation='elu'))
optimizer = keras.optimizers.RMSprop(lr=0.01) 
model.compile(loss='mean_squared_error', optimizer=optimizer)
model.summary()

model.fit(x,y,batch_size=5,epochs=2)

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_3 (LSTM)                (None, 256)               264192    
_________________________________________________________________
dense_5 (Dense)              (None, 100)               25700     
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 101       
Total params: 289,993
Trainable params: 289,993
Non-trainable params: 0
_________________________________________________________________
Epoch 1/2
5000/5000 [==============================] - 30s 6ms/step - loss: 15388591.1118
Epoch 2/2
5000/5000 [==============================] - 29s 6ms/step - loss: 14894812.2716


In [6]:
#After training the model, we can input one role from x and to see we we got
sample = x[1]
sample = sample.reshape(1,50,1)
model.predict(sample,verbose=0)

array([[2153.7476]], dtype=float32)

In [7]:
y[1]

array([7923.2038213])

In [8]:
x[1]

array([[ 2528.96273773],
       [ 6245.5004948 ],
       [ 4255.57845103],
       [ 1320.07958033],
       [ 1133.71467295],
       [ 1073.02168437],
       [ 1225.07082628],
       [ 4184.40239505],
       [ 3962.22758567],
       [  497.42956858],
       [ 5199.85623181],
       [  231.17644002],
       [  503.51615953],
       [ 4175.23209719],
       [ 2855.8607256 ],
       [  992.4817253 ],
       [ 2994.58059585],
       [ 5328.28440267],
       [  313.75868116],
       [13673.76321346],
       [ 4024.46417614],
       [ 1381.38704584],
       [ 1752.45387534],
       [  197.78753663],
       [ 1239.69319844],
       [ 1488.652077  ],
       [ 1904.73951631],
       [ 2841.27776831],
       [ 2718.54688445],
       [ 2470.92533894],
       [ 7493.08912198],
       [ 4660.2923941 ],
       [ 4859.8994989 ],
       [  878.79916899],
       [  792.67134431],
       [11151.09059309],
       [  561.92792668],
       [17846.30269698],
       [ 4382.07175339],
       [ 1575.3589973 ],


In [1]:
import pandas as pd

In [3]:
d = pd.read_csv("/Users/peng/Downloads/multilabel.csv")
df = pd.DataFrame(data = d)

In [8]:
print("'" + "blue" + "',")

'blue',


In [12]:
for i in df['superclass']:
    i = "'" + i + "',"
    print(i)

'Bagel',
'Bagel',
'Bagel',
'Bagel',
'Bagel',
'Beans',
'Beans',
'Beef',
'Beef',
'Beef',
'Beef',
'Beef',
'Beef',
'Beef',
'Beef',
'Beef',
'Beef',
'Beverage',
'Bread',
'Bread',
'Bread',
'bread',
'Bread',
'Bread',
'Bread',
'Bread',
'Bread',
'Bread',
'Bread',
'Bread',
'Bulgur',
'Burger',
'Burger',
'Burger',
'Burger',
'Burrito',
'Burrito',
'Burrito',
'Cake',
'Cake',
'Cake',
'Cake',
'Cake',
'Cake',
'Cake',
'Casserole',
'Casserole',
'Casserole',
'Cheese',
'Cheese',
'Cheese',
'Cheese',
'Cheese',
'Cheese',
'Cheese',
'Cheese',
'Cheese',
'Cheese',
'Cheese',
'Chicken',
'Chicken',
'Chicken',
'Chicken',
'Chicken',
'Chicken',
'Chicken',
'Chicken',
'Chicken',
'Chicken',
'Chicken',
'Chicken',
'Chicken',
'Chips',
'Chips',
'Chips',
'Chips',
'Chips',
'Chocolate Truffles',
'condiment',
'Condiment',
'Cookies',
'Cookies',
'Cookies',
'Cookies',
'Cookies',
'Cookies',
'Cookies',
'Cookies',
'Corn',
'Corn Bread',
'Crepes',
'Croissant',
'Croissant',
'Croissant',
'Croissant',
'Culture Food: Israeli',
'Deli Meat',
'De

label  superclass
0         blueberry_bagel       Bagel
1          jalapeno_bagel       Bagel
2             onion_bagel       Bagel
3             plain_bagel       Bagel
4        poppy_seed_bagel       Bagel
5             black_beans       Beans
6        cannellini_beans       Beans
7             beef_jerkey        Beef
8             beef_tagine        Beef
9             corned_beef        Beef
10           filet_mignon        Beef
11   grilled_beef_skewers        Beef
12    grilled_flank_steak        Beef
13             osso_bucco        Beef
14              prime_rib        Beef
15                   ribs        Beef
16             roast_beef        Beef
17                shikhye    Beverage
18             burger_bun       Bread
19   cinamom_raisin_bread       Bread
20               croutons       Bread
21               focaccia       bread
22           garlic_bread       Bread
23            kiaser_roll       Bread
24             pita_bread       Bread
25         plain_baguette       Bread
26          potatoe_bread       Bread
27              rye_bread       Bread
28   wheat_sandwich_bread       Bread
29      whole_grain_bread       Bread
..                    ...         ...
359     steamed_asparagus   Vegetable
360                tomato   Vegetable
361                turnip   Vegetable
362    yellow_bell_pepper   Vegetable
363               arugula  Vegetables
364         bamboo_shoots  Vegetables
365          bean_sprouts  Vegetables
366          black_olives  Vegetables
367              bok_choy  Vegetables
368      brussels_sprouts  Vegetables
369               carrots  Vegetables
370    cauliflower_gratin  Vegetables
371                celery  Vegetables
372             chickpeas  Vegetables
373       creamed_spinach  Vegetables
374                fennel  Vegetables
375                  kale  Vegetables
376                 leeks  Vegetables
377               lettuce  Vegetables
378                  okra  Vegetables
379               parsnip  Vegetables
380          string_beans  Vegetables
381       stuffed_peppers  Vegetables
382               taboule  Vegetables
383       vegetable_curry  Vegetables
384              zucchini  Vegetables
385              blt_wrap        Wrap
386   chicken_caesar_wrap        Wrap
387   ham_and_cheese_wrap        Wrap
388          greek_yogurt      Yogurt

[389 rows x 2 columns]